const config = require('../config/config');
const pool = require('../config/database');
const nodemailer = require('nodemailer');
const { mailtrapUserName, mailtrapPassword } = require('../config/config');
const transporter = nodemailer.createTransport({
    host: "smtp.mailtrap.io",
    port: 2525,
    auth: {
      user: mailtrapUserName, //generated by Mailtrap
      pass: mailtrapPassword //generated by Mailtrap
    }
});

// Register (processRegister)
module.exports.createUser = (fullname, email, password, callback) => {
        console.log('Checking the input parameter variable content.');
        console.log(fullname, email, password);

        userDataQuery = `INSERT INTO user (fullname, email, user_password, role_id) VALUES (?,?,?,2)` ;

            pool.getConnection((err, connection) => {
                if (err) {
                    console.log('Database connection error ', err);
                    callback(null, err);
                } else {
                    connection.query(userDataQuery,[fullname, email, password], (err, rows) => {
                        if (err) {
                            callback(null, err);
                        } else {
                            callback(rows, null);
                        }
                        connection.release();
                    });
                }
            });


    } // End of createUser

// Admin Update Role (processUpdateOneUser)
module.exports.updateUser = (recordId, newRoleId) => {
        console.log('updateUser method is called');

        userDataQuery = `UPDATE user SET role_id = ? WHERE user_id = ?`;

        return new Promise((resolve, reject) => {
            //I referred to https://www.codota.com/code/javascript/functions/mysql/Pool/getConnection
            //to prepare the following code pattern which does not use callback technique (uses Promise technique)
            pool.getConnection((err, connection) => {
                if (err) {
                    console.log('Database connection error ', err);
                    resolve(err);
                } else {
                    console.log('Connected to Database for UPDATE ');
                    connection.query(userDataQuery,[newRoleId,recordId], (err, rows) => {
                        if (err) {
                            console.log("error after connecting to database" + err);
                            reject(err);
                        } else {
                            resolve(rows);
                        }
                        connection.release();
                    });
                }
            });
        }); //End of new Promise object creation

    } //End of updateUser

// Admin Search User by Name ( Manage Users ) (processGetUserData) + User send email (processSendInvitation)
// XSS trigger
module.exports.getUserData = (pageNumber, search) => {
        console.log('getUserData method is called.');

        const page = pageNumber;
        if (search == null) { search = ''; };
        const limit = 4; //Due to lack of test files, I have set a 3 instead of larger number such as 10 records per page
        const offset = (page - 1) * limit;

        //If the user did not provide any search text, the search variable
        //should be null. The following console.log should output undefined.
        //console.log(search);
        //-------------- Code which does not use stored procedure -----------
        //Query for fetching data with page number, search text and offset value

        if ((search == '') || (search == null)) {
            console.log('Prepare query without search text');

            userDataQuery = `SELECT user_id, fullname, email, role_name 
        FROM user INNER JOIN role ON user.role_id = role.role_id LIMIT ${limit} OFFSET ${offset};
        SET @total_records =(SELECT count(user_id) FROM user    );SELECT @total_records total_records; `;
        } else {
            userDataQuery = `SELECT user_id, fullname, email, role_name 
        FROM user INNER JOIN role ON user.role_id = role.role_id AND fullname LIKE '%${search}%'  LIMIT ${limit} OFFSET ${offset};
    SET @total_records =(SELECT count(user_id) FROM user WHERE fullname LIKE '%${search}%' );SELECT @total_records total_records;`;
        }

        return new Promise((resolve, reject) => {
            //I referred to https://www.codota.com/code/javascript/functions/mysql/Pool/getConnection
            //to prepare the following code pattern which does not use callback technique (uses Promise technique)
            pool.getConnection((err, connection) => {
                if (err) {
                    console.log('Database connection error ', err);
                    resolve(err);
                } else {

                    connection.query(userDataQuery, [search, offset, limit], (err, results) => {
                        if (err) {
                            reject(err);
                        } else {
                            console.log('Accessing total number of rows : ', results[2][0].total_records);
                            resolve(results);
                        }
                        connection.release();
                    });
                }
            });
        }); //End of new Promise object creation

    } //End of getUserData

// Admin Update Role (processGetOneUserData) + User Send Email (processSendInvitation)
// SQL INJECTION 
/*
the recordId is getting directly from the URL to retrieve all the information
*/
module.exports.getOneUserData = function(recordId) {
        console.log('getOneUserData method is called.');
        console.log('Prepare query to fetch one user record');

        userDataQuery = `SELECT user_id, fullname, email, user.role_id, role_name 
        FROM user INNER JOIN role ON user.role_id = role.role_id WHERE user_id = ?`;

        return new Promise((resolve, reject) => {
            //I referred to https://www.codota.com/code/javascript/functions/mysql/Pool/getConnection
            //to prepare the following code pattern which does not use callback technique (uses Promise technique)
            pool.getConnection((err, connection) => {
                if (err) {
                    console.log('Database connection error ', err);
                    resolve(err);
                } else {
                    connection.query(userDataQuery,[recordId], (err, results) => {
                        if (err) {
                            reject(err);
                        } else {
                            resolve(results);
                        }
                        connection.release();
                    });
                }
            });
        }); //End of new Promise object creation

    } //End of getOneUserData

// Admin Search Submission by Email ( Manage Submission ) (processGetSubmissionsbyEmail)
// SQL INJECTION 
/*
the emailsearch is getting directly from the URL to retrieve all the information
*/
module.exports.getOneUserDataByEmail = function(search) {
        console.log('getOneUserDataByEmail method is called.');
        console.log('Prepare query to fetch one user record');

        userDataQuery = `SELECT user_id, fullname, email, user.role_id, role_name 
        FROM user INNER JOIN role ON user.role_id = role.role_id WHERE email= ?`;

        return new Promise((resolve, reject) => {
            //I referred to https://www.codota.com/code/javascript/functions/mysql/Pool/getConnection
            //to prepare the following code pattern which does not use callback technique (uses Promise technique)
            pool.getConnection((err, connection) => {
                if (err) {
                    console.log('Database connection error ', err);
                    resolve(err);
                } else {
                    connection.query(userDataQuery,[search], (err, results) => {
                        if (err) {
                            reject(err);
                        } else {
                            resolve(results);
                        }
                        connection.release();
                    });
                }
            });
        }); //End of new Promise object creation

    } //End of getOneUserDataByEmail

// User Update Design (processGetOneDesignData)
// SQL INJECTION 
/*
the recordId is getting directly from the URL to retrieve all the information
*/
module.exports.getOneDesignData = function(recordId) {
        console.log('getOneDesignData method is called.');
        console.log('Prepare query to fetch one design record');

        userDataQuery = `SELECT file_id,cloudinary_file_id,cloudinary_url,design_title,design_description FROM file WHERE file_id= ? `;

        return new Promise((resolve, reject) => {
            //I referred to https://www.codota.com/code/javascript/functions/mysql/Pool/getConnection
            //to prepare the following code pattern which does not use callback technique (uses Promise technique)
            pool.getConnection((err, connection) => {
                if (err) {
                    console.log('Database connection error ', err);
                    resolve(err);
                } else {
                    connection.query(userDataQuery,[recordId], (err, results) => {
                        if (err) {
                            reject(err);
                        } else {
                            resolve(results);
                        }
                        connection.release();
                    });
                }
            });
        }); //End of new Promise object creation

    } //End of getOneDesignData

// User Update Design (processUpdateOneDesign)
// SQL INJECTION
/*
the recordId, title and description is getting directly from the URL to update the information
the database query is built via a String concatenation
*/
module.exports.updateDesign = (recordId, title, description) => {
        console.log('updateDesign method is called');

        userDataQuery = (`UPDATE file SET design_title = ? , design_description = ? WHERE file_id = ?`);
        return new Promise((resolve, reject) => {
            //I referred to https://www.codota.com/code/javascript/functions/mysql/Pool/getConnection
            //to prepare the following code pattern which does not use callback technique (uses Promise technique)
            pool.getConnection((err, connection) => {
                if (err) {
                    console.log('Database connection error ', err);
                    resolve(err);
                } else {
                    connection.query(userDataQuery,[title,description,recordId], (err, rows) => {
                        if (err) {
                            reject(err);
                        } else {
                            resolve(rows);
                        }
                        connection.release();
                    });
                }
            });
        }); //End of new Promise object creation

    } //End of updateDesign

// User Send Email (processSendInvitation)
// XSS
module.exports.createOneEmailInvitation =  (userData,recipientName, recipientEmail) => {
    
    return new Promise((resolve, reject) => {
        console.log('userService createOneEmailInvitation is running');
        console.log('Inspect whether the userData variable has content:')
        console.log(userData);

  // send mail with defined transport object
  try{
  let info =  transporter.sendMail({
    from: `${userData.fullname}<${userData.email}>`, // sender address
    to: recipientEmail, // list of receivers
    subject: "Hello from Bee competition system admin", // Subject line
    text: `Hi ${recipientName} You have been invited by your friend, ${userData.fullname} to participate in a competition at http://localhost:3001`, // plain text body
    html: `Hi ${recipientName} You have been invited by your friend, ${userData.fullname} to participate in a competition at http://localhost:3001`, // html body
  });
  resolve({status:'success',description:'Email sent'});
}catch(error){
  reject({status:'fail', description: error});
}
 }); //End of new Promise object creation
} //End of createOneEmailInvitation

// ADDED
module.exports.getRoleId = function() {
    console.log('getRoleId method is called.');
    console.log('Prepare query to fetch role.id record');

    roleDataQuery = `SELECT role_id FROM role`;

    return new Promise((resolve, reject) => {
        pool.getConnection((err, connection) => {
            if (err) {
                console.log('Database connection error ', err);
                resolve(err);
            } else {
                connection.query(roleDataQuery,[], (err, results) => {
                    if (err) {
                        reject(err);
                    } else {
                        resolve(results);
                    }
                    connection.release();
                });
            }
        });
    }); //End of new Promise object creation

} //End of getRoleId

module.exports.getRole = function(userId) {
    console.log('getRole method is called.');
    console.log('Prepare query to fetch role.id record');

    roleDataQuery = `SELECT role.role_name 
    FROM user INNER JOIN role ON user.role_id = role.role_id WHERE user_id = ? ;`;

    return new Promise((resolve, reject) => {
        pool.getConnection((err, connection) => {
            if (err) {
                console.log('Database connection error ', err);
                resolve(err);
            } else {
                connection.query(roleDataQuery,[userId], (err, results) => {
                    if (err) {
                        reject(err);
                    } else {
                        resolve(results);
                    }
                    connection.release();
                });
            }
        });
    }); //End of new Promise object creation

} //End of getRoleId
